# Build time image: used to prepare the environment of the production run time imag
FROM node:18-alpine AS builder
WORKDIR /app

# clean install dependencies (if deps don't match between package-lock.json and package.json, return error)
# => ensure same dependecy tree for each build and coherence between developpers' dependencies
COPY package*.json ./
RUN npm ci

# Create the db schema for prisma to use
COPY ./prisma ./prisma
RUN npm run prisma:generate
# we are only generating the prisma schema, and not applying migrations, 
# because building the image should not modify every time the production DB

# Compile the src files
COPY ./tsconfig.json ./
COPY ./src ./src
RUN npm run build
# compiled files end up in ./dist, as defined in tsconfig.json "outDir" argument


# Runtime image =======================================
FROM node:18-alpine
WORKDIR /app

ENV NODE_ENV=production

# install only production dependencies
COPY package*.json ./
RUN npm ci --omit=dev

# installing missing dependency on Alpine (using the alpine package manager apk)
# required for prisma to run. 
RUN apk add --no-cache openssl

# Grabbing the compiled files and prisma schema/dependencies from the builder image
COPY --from=builder ./app/dist ./dist
COPY --from=builder ./app/prisma ./prisma
COPY --from=builder ./app/node_modules/.prisma ./node_modules/.prisma

# Launch the compiled server
EXPOSE 3000
CMD ["npm", "start"]